const cities = [
    { name: "Abidjan", country: "Côte d'Ivoire" },
    { name: "Abu Dhabi", country: "Émirats Arabes Unis" },
    { name: "Accra", country: "Ghana" },
    { name: "Addis Ababa", country: "Éthiopie" },
    { name: "Ahmedabad", country: "Inde" },
    { name: "Algiers", country: "Algérie" },
    { name: "Amsterdam", country: "Pays-Bas" },
    { name: "Ankara", country: "Turquie" },
    { name: "Athens", country: "Grèce" },
    { name: "Atlanta", country: "USA" },
    { name: "Auckland", country: "Nouvelle-Zélande" },
    { name: "Baghdad", country: "Irak" },
    { name: "Baku", country: "Azerbaïdjan" },
    { name: "Bangalore", country: "Inde" },
    { name: "Bangkok", country: "Thaïlande" },
    { name: "Barcelona", country: "Espagne" },
    { name: "Beijing", country: "Chine" },
    { name: "Beirut", country: "Liban" },
    { name: "Belgrade", country: "Serbie" },
    { name: "Berlin", country: "Allemagne" },
    { name: "Bogotá", country: "Colombie" },
    { name: "Boston", country: "USA" },
    { name: "Brussels", country: "Belgique" },
    { name: "Bucharest", country: "Roumanie" },
    { name: "Budapest", country: "Hongrie" },
    { name: "Buenos Aires", country: "Argentine" },
    { name: "Cairo", country: "Égypte" },
    { name: "Cape Town", country: "Afrique du Sud" },
    { name: "Caracas", country: "Venezuela" },
    { name: "Casablanca", country: "Maroc" },
    { name: "Chennai", country: "Inde" },
    { name: "Chicago", country: "USA" },
    { name: "Copenhagen", country: "Danemark" },
    { name: "Dakar", country: "Sénégal" },
    { name: "Dallas", country: "USA" },
    { name: "Delhi", country: "Inde" },
    { name: "Dhaka", country: "Bangladesh" },
    { name: "Dubai", country: "Émirats Arabes Unis" },
    { name: "Dublin", country: "Irlande" },
    { name: "Durban", country: "Afrique du Sud" },
    { name: "Frankfurt", country: "Allemagne" },
    { name: "Geneva", country: "Suisse" },
    { name: "Hanoi", country: "Vietnam" },
    { name: "Harare", country: "Zimbabwe" },
    { name: "Helsinki", country: "Finlande" },
    { name: "Ho Chi Minh City", country: "Vietnam" },
    { name: "Hong Kong", country: "Chine" },
    { name: "Istanbul", country: "Turquie" },
    { name: "Jakarta", country: "Indonésie" },
    { name: "Johannesburg", country: "Afrique du Sud" },
    { name: "Kabul", country: "Afghanistan" },
    { name: "Kampala", country: "Ouganda" },
    { name: "Karachi", country: "Pakistan" },
    { name: "Kathmandu", country: "Népal" },
    { name: "Kiev", country: "Ukraine" },
    { name: "Kigali", country: "Rwanda" },
    { name: "Kuala Lumpur", country: "Malaisie" },
    { name: "Lagos", country: "Nigeria" },
    { name: "Lahore", country: "Pakistan" },
    { name: "Lima", country: "Pérou" },
    { name: "Lisbon", country: "Portugal" },
    { name: "London", country: "Royaume-Uni" },
    { name: "Los Angeles", country: "USA" },
    { name: "Madrid", country: "Espagne" },
    { name: "Manila", country: "Philippines" },
    { name: "Mexico City", country: "Mexique" },
    { name: "Milan", country: "Italie" },
    { name: "Montreal", country: "Canada" },
    { name: "Moscow", country: "Russie" },
    { name: "Mumbai", country: "Inde" },
    { name: "Nairobi", country: "Kenya" },
    { name: "New York", country: "USA" },
    { name: "Oslo", country: "Norvège" },
    { name: "Paris", country: "France" },
    { name: "Prague", country: "République Tchèque" },
    { name: "Rio de Janeiro", country: "Brésil" },
    { name: "Rome", country: "Italie" },
    { name: "San Francisco", country: "USA" },
    { name: "Santiago", country: "Chili" },
    { name: "São Paulo", country: "Brésil" },
    { name: "Seoul", country: "Corée du Sud" },
    { name: "Shanghai", country: "Chine" },
    { name: "Singapore", country: "Singapour" },
    { name: "Stockholm", country: "Suède" },
    { name: "Sydney", country: "Australie" },
    { name: "Tokyo", country: "Japon" },
    { name: "Toronto", country: "Canada" },
    { name: "Vienna", country: "Autriche" },
    { name: "Warsaw", country: "Pologne" },
    { name: "Washington D.C.", country: "USA" },
    { name: "Zurich", country: "Suisse" },
  ];
  
  export default cities;
  